auth_login/urls.py
from django.urls import path
from auth_login import views


app_name = 'auth_login'

urlpatterns = [
    path('',views.login, name='login'),
    #path('logout', views.logout, name='logout'),
]

client/urls.py
from django.urls import path
from client import views
from client import api
#from auth_login import views

app_name = 'client'

urlpatterns = [
    # [Módulo base]
    path('home_base',
        views.home_client_base,
        name='home_base'),

    # [Módulo Notificaciones]
    path('notificaciones/<int:station_id>',
        views.notifications,
        name='notifications'),

    # [Modulo galeria]
    path('galeria/<int:station_id>',
        views.gallery,
        name='gallery'),
    # [Modulo galeria] - detail
    path('galeria/detalle/<int:station_id>/<int:gallery_id>',
        views.gallery_detail,
        name='gallery_detail'),

    # [Modulo Estación]
    path('estacion/<int:station_id>',
        views.station_data,
        name='station'),

    # [Modulo Taxonomía] - [monitoring records] - processing
    path('taxon/procesamiento/<int:station_id>',
        views.monitoring_processing,
        name='monitoring_processing'),
    # [Modulo Taxonomía] - [monitoring records] - update (modal in proccesing)
    path('taxon/procesamiento/actualizar_registro/<int:monitoring_id>',
        views.monitoring_update,
        name='monitoring_update'),
    # TODO: [Modulo Taxonomía] - [monitoring records] - list --> new feature
    # TODO: [Modulo Taxonomía] - [monitoring records] - delete --> new feature

    # [Modulo Taxonomía] - [detection records] - list
    path('taxon/lista_detecciones/<int:station_id>',
        views.detection_list,
        name='detection_list'),
    # [Modulo Taxonomía] - [detection records] - create
    path('taxon/procesamiento/crear_deteccion/<int:monitoring_id>',
        views.detection_create,
        name='detection_create'),
    # TODO: [Modulo Taxonomía] - [detection records] - update --> new feature
    # TODO: [Modulo Taxonomía] - [detection records] - delete --> new feature
    # Funciones Get para cargar formulario concatenado
    path('get/animals/', views.get_animal, name='get_animal'),
    path('get/animalsclass/', views.get_animal_class, name='get_animal_class'),
    path('get/animalsorder/', views.get_animal_order, name='get_animal_order'),
    path('get/animalsfamily/', views.get_animal_family, name='get_animal_family'),
    path('get/animalsgenus/', views.get_animal_genus, name='get_animal_genus'),
    path('get/animalsspecies/', views.get_animal_species, name='get_animal_species'),
    path('get/animalsorigin/', views.get_animal_origin, name='get_animal_origin'),

    # [Get and Post data] - API
    path('api/home', api.HomeClientAPIView.as_view(), 
        name='home_api'),
    # [Get and Post data] - Detections csv
    path('gestion/csv/<int:station_id>/<int:getcsv>',views.get_csv, name='get_csv'),
    
]

main/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('manager/', include('manager.urls')),
    path('client/', include('client.urls')),
    path('', include('auth_login.urls')),
    #path('animalkingdom', include('animalkingdom.urls')),
]

client/models.py
from django.db import models
from django.core import validators
# External models import
from django.contrib.auth.models import User
from manager.models import FaunoProject
from animalkingdom.models import(
        Animal, AnimalName,
        AnimalClass, AnimalOrder,
        AnimalFamily, AnimalGenus,
        AnimalSpecies, AnimalOrigin
)

from client.utils import definitions, validators


class Station(models.Model):

    """
    + Clase Station
        - Descripción: Identifica la estacion asociada al proyecto Fauno
        - Relación: FaunoProject [1-n] Station
        - Atributos:
            - fauno_project : Foreign key - objeto fauno_project asociado
            - longitude: parámetro  de coordenada geografica de la estacion
            - latitude: parámetro  de coordenada geografica de la estacion
            - habitat: habitat del entorno donde se instalo la estacion
                - native_forest
                - meadow (pradera?)
                - plantation
                - scrubland (matorrales?)
            - target: qué especies se espera encontrar en la zona donde se 
                    ubica la estación
            - status: si la estación está activa o inactiva
                - active
                - inactive
    """
    # Fk
    fauno_project = models.ForeignKey(FaunoProject, on_delete = models.CASCADE)
    # Atributos
    latitude = models.FloatField()
    longitude = models.FloatField()
    habitat = models.CharField(
            max_length=20,
            choices=definitions.habitats,
            default="native_forest")
    target = models.CharField(
            max_length=20,
            default=None,
            validators= validators.validator_target_length)
    status = models.CharField(
            max_length=20,
            choices=definitions.station_status,
            default="inactive")

    def __str__(self):
        return '(%s - %s)(%s)' % (self.fauno_project.name,
                                self.fauno_project.pk,
                                self.pk)

    class Meta:
        verbose_name_plural = "Stations"


class UserXStation(models.Model):

    """
    + Clase UserXFaunoProject
        - Descripcion: clase intermedia de relación [n:n] entre usuario y 
                        proyectos Fauno
        - Relación: User, Station [1:n] UserXStation
        - Atributos
            - user: Foreign key - objeto user asociado
            - fauno_project: Foreign key - objeto fauno_project asociado
    """
    # Fk
    user  = models.ForeignKey(
            User,
            on_delete = models.CASCADE)
    station  = models.ForeignKey(
            Station,
            on_delete = models.CASCADE)

    def __str__(self):
        return '%s - %s (%s)' % (self.user.username, self.station.fauno_project.name,self.pk)

    class Meta:
        verbose_name_plural = "Station Users"


class Hardware(models.Model):
    
    """
    + Clase Hardware
        - Descripcion: Partes que componen la estacion: raspberry, sd, camara,
        - Relacion: Station [1-n] Hardware
        - Atributos:
            - station: Foreign key - objeto station asociado
            - hardware_type: raspberry, sd-card, camera, etc
            - status: working, on revision, disabled
            - model: modelo del equipo
            - last_install_date: última vez que este equipo fue instalado en la
                                estacion ya sea porque es nuevo, fue reparado o
                                actualizado.
            - last_uninstall_date: última vez que este equipo fue desinstalado 
                                de la estacion ya sea porque debe ser reparado,
                                actualizado o debe instalarse en otra estación 
                                Fauno.
            - usage_counter: contador con la cantidad de veces que el hardware 
                            ha sido instalado en diferentes estaciones, o en la
                            misma si éste fue reparado o actualizado.
    """

    # Fk
    station = models.ForeignKey(Station, on_delete = models.CASCADE)
    # Atributos
    hardware_type  = models.CharField(
            max_length = 20,
            choices = definitions.hardware_types, 
            default="raspberry")
    status = models.CharField(
            max_length = 15,
            choices = definitions.hardware_status,
            default="working") 
    model = models.CharField(
            max_length=45,
            default=None,
            validators=validators.validator_model_length)
    last_install_date = models.DateField(
            auto_now=False,
            blank=True,
            null=True)
    last_uninstall_date = models.DateField(
            auto_now=False,
            blank=True,
            null=True)
    usage_counter = models.IntegerField(default=0)

    def __str__(self):
        return '(%s) (%s - %s)' % (self.hardware_type,
                                self.station.fauno_project.name,
                                self.station.fauno_project.pk)

    class Meta:
        verbose_name_plural = "Hardwares"


class HardwareLog(models.Model):
    
    """
    + Clase HardwareLog
        - Descripcion: Log con el historial de uso del equipo
        - Relacion: Hardware [1:n] HardwareLog
        - Atributos:
            - hardware: Foreign key - objeto hardware asociado
            - log_type: tipos de log:
                - maintenance
                - failure_revision
                - upgrade
                - replacement
            - log_datetime: fecha
            - log_detail: descripción
    """

    # Fk
    hardware = models.ForeignKey(Hardware, on_delete = models.CASCADE)
    # Atriutos
    log_type = models.CharField(
            max_length = 20,
            choices = definitions.log_types,
            default="maintenance")
    log_datetime = models.DateField(auto_now=False)
    log_datail = models.CharField(
            max_length=100,
            default=None,
            validators= validators.validator_log_length)

    def __str__(self):
        return '(%s - %s - %s) (%s)' % (
                self.hardware.hardware_type,
                self.hardware.station.fauno_project.name,
                self.hardware.station.fauno_project.pk,
                self.pk)

    class Meta:
        verbose_name_plural = "Hardware Logs"


class Monitoring(models.Model):
    
    """
    + Clase Monitoring
        - Descripcion: Almacena los datos de las notificaciones de la estación
                     (status/monitoreo )
        - Relacion: Station [0:n] Monitoring
        - Atributos:
            - station: Foreign key - objeto station asociado
            - monitoring_datetime: fecha:hr
            - record: boolean - (old version: animal_alert)
                - True: es un registro por movimiento
                - False: es monitoreo de funcionamiento
            - false_positive(*): boolean
                - True: registro de movimiento sin elementos detectados
                - False: registro de movimiento con elementos detectados
            - elements_counter(*)(**): cantidad de elementos en la imagen/video
            - human_presence(*)(**): boolean
                - True: registro de movimiento con humanos detectados
                - False: registro de movimiento sin humanos detectados
            - status(*): estado de revisión del monitoreo
                - viewed: visto por el usuario
                - pending_monitoring: falta actualizar datos de Monitoreo
                - pending_taxonomy: falta actualizar datos de Taxonomia
                - reviewed: Ya fue revisado
            - image_link: link de la imagen en s3
            - video_link: link del video en s3
            - in_gallery: boolean
                - True: Se visualizará desde la galeria
                - False: No se visualizará desde la galeria
            - notes(*): apuntes de lo observado en img/video capturado

        (*) Datos ingresados por el usuario. 
        (**) Datos que en  futuras etapas seran actualizadas con ML
    """

    # Fk
    station = models.ForeignKey(Station, on_delete = models.CASCADE)
    #Atributos
    monitoring_datetime = models.DateTimeField(auto_now=False)
    record = models.BooleanField(default=False) # old version: animal_alert
    false_positive = models.BooleanField(blank=True, default=True)
    elements_counter = models.IntegerField(blank=True, null=True)
    human_presence = models.BooleanField(blank=True, default=False)
    status = models.CharField(
        max_length = 20,
        choices = definitions.monitoring_status,
        blank=True,
        default="viewed")
    image_url = models.CharField(max_length = 150,blank=True, default="")
    video_url = models.CharField(max_length = 150,blank=True, default="")
    in_gallery = models.BooleanField(blank=True, default=False)
    notes = models.TextField(blank=True, null=True)

    def __str__(self):
        return ' (%s - %s) (%s)' % (
                self.station.fauno_project.name,
                self.station.fauno_project.pk,
                self.pk)
        
    class Meta:
        verbose_name_plural = "Monitoring"


# NEW MODEL FOR TAXONOMY DATA
class DetectedAnimal(models.Model):
    #pk auto id
    # blank=True, null=True
    monitoring = models.ForeignKey(Monitoring, on_delete = models.CASCADE,
                                blank=True, null=True,default=1)
    animal = models.ForeignKey(Animal, on_delete = models.CASCADE,
                                blank=True, null=True,default=1)
    animal_name = models.ForeignKey(AnimalName, on_delete = models.CASCADE,
                                blank=True, null=True,default=1)
    animal_class = models.ForeignKey(AnimalClass, on_delete = models.CASCADE,
                                blank=True, null=True,default=1)
    animal_order = models.ForeignKey(AnimalOrder, on_delete = models.CASCADE,
                                blank=True, null=True,default=1)

client/forms.py
from django import forms
from client.models import Monitoring, DetectedElement
  
  
# Formulario de actualización de monitoreo
class MonitoringForm(forms.ModelForm):
  
    # create meta class
    class Meta:
        # Model to be used
        model = Monitoring

        labels = {
            'id':'ID',
            'record':'Registro',
            'false_positive':'Falso positivo',
            'elements_counter':'N° Elementos',
            'human_presence':'Presencia Humana',
            'in_gallery':'Galería',
            'status':'Estado de revisión',
            'notes':'Notas'
        }
  
        # Fields to be used
        fields = [
            "id",
            "record",
            "false_positive",
            "elements_counter",
            "human_presence",
            "in_gallery",
            "status",
            "notes"
        ]

# Formulario de actualización de taxoinomía
class DetectedElementForm(forms.ModelForm):
  
    def __init__(self, *args, **kwargs):
        super(DetectedElementForm, self).__init__(*args, **kwargs)
        
        self.fields['monitoring'].widget = forms.HiddenInput()


    # create meta class
    class Meta:
        # Model to be used
        model = DetectedElement

        labels = {
            'taxonomy_kingdom':'Reino',
            'taxonomy_phyllum':'Phyllum',
            'taxonomy_class':'Clase',
            'taxonomy_common_class':'Clase(común)',
            'taxonomy_order':'Orden',
            'taxonomy_common_order':'Orden(común)',
            'taxonomy_family':'Familia',
            'taxonomy_genus':'Género',
            'taxonomy_species':'Especie',
            'taxonomy_common_species':'Especie(común)',
            'taxonomy_origin':'Origen',
            'lifehistory_behavior':'Comportamiento',
            'lifehistory_health_condition':'Condición de salud',
            'notes':'Observaciones'
        }


        # help_texts = {
        #     'taxonomy_kingdom': 'Some useful help text.',
        # }


        # Fields to be used
        fields = '__all__'  
        # fields = [

        #     "id",
        #     "monitoring",
        #     "taxonomy_kingdom",
        #     "taxonomy_phyllum",
        #     "taxonomy_class",
        #     "taxonomy_common_class",
        #     "taxonomy_order",
        #     "taxonomy_common_order",
        #     "taxonomy_family",
        #     "taxonomy_genus",
        #     "taxonomy_species",
        #     "taxonomy_common_species",
        #     "taxonomy_origin",
        #     "lifehistory_behavior", 
        #     "lifehistory_health_condition",
        #     "notes"
        # ]
        

client/templates/client_base_modal.html
<!DOCTYPE html>
<html lang="es-cl">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>
        {% block title %} {% endblock %}
    </title>
    
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/css/bootstrap.min.css"
        integrity="sha384-B0vP5xmATw1+K9KRQjQERJvTumQW0nPEzvF6L/Z6nronJ3oUOFUFpCjEUQouq2+l" crossorigin="anonymous">
    {% block extra_css %}
    {% endblock %}

</head>

<body>

    {% block content %}
    {% endblock %}


<!-- Custom js -->
{% block extra_js%}
{% endblock %}
<!-- End Custom js -->
</body>

</html>

client/templates/client_detection_create.html
{% extends 'client_base_modal.html' %}
{% load bootstrap4 %}

{% block extra_css %}
    <link href="https://cdn.jsdelivr.net/npm/select2@4.1.0-beta.1/dist/css/select2.min.css" rel="stylesheet"/>
{% endblock %}

{% block content %}

<div class="main-panel">
    <form method="POST" class="form-horizontal">
        {% csrf_token %}

        <div class="form-group">
            <div class="col-md-9">
                <label>Nombre</label>
                <select style="width:50%" class="select2 form-control"  name="animal_name" id="id_animal_name">
                    <option>No identificado</option>
                </select>
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-9">
                <label>Clase</label>
                <select style="width:50%" class="select2 form-control" name="animal_class" id="id_animal_class">
                    <option>No identificado</option>
                </select>
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-9">
                <label>Orden</label>
                <select style="width:50%" class="select2 form-control"  name="animal_order" id="id_animal_order">
                    <option>No identificado</option>
                </select>
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-9">
                <label>Familia</label>
                <select style="width:50%" class="select2 form-control"  name="animal_family" id="id_animal_family">
                    <option>No identificado</option>
                </select>
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-9">
                <label>Género</label>
                <select style="width:50%" class="select2 form-control"  name="animal_genus" id="id_animal_genus">
                    <option>No identificado</option>
                </select>
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-9">
                <label>Especie</label>
                <select style="width:50%" class="select2 form-control"  name="animal_species" id="id_animal_species">
                    <option>No identificado</option>
                </select>
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-9">
                <label>Origen</label>
                <select style="width:50%" class="select2 form-control"  name="animal_origin" id="id_animal_origin">
                    <option>No identificado</option>
                </select>
            </div>
        </div>
        <!-- No concatenated atributes-->
        <div class="form-group">
            <div class="col-md-9">
                <label>Comportamiento</label>
                <select style="width:50%" class="select2 form-control"  name="lifehistory_behavior" id="id_lifehistory_behavior">
                    <option>Sin información</option>
                    <option>Cazando</option>
                    <option>De paso</option>
                    <option>Alimentándose</option>
                </select>
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-9">
            <label>Condición de Salud</label>
                <select style="width:50%" class="select2 form-control"  name="lifehistory_health_condition" id="id_lifehistory_health_condition">
                    <option>Sin información</option>
                    <option>Sano</option>
                    <option>Enfermo</option>
                </select>
            </div>
        </div>

        <div class="form-group">
            <label class="col-md-2 control-label">Notas</label>
            <label class="col-md-2 control-label" style="color: lightslategray">Escribe aquí tus comentarios</label>
            <div class="col-md-9">
                <textarea name="notes"  id="id_notes" class="text-black-50"rows="10" cols="40"></textarea>
            </div>
        </div>
        <br>

        <button onclick="sendData()" class="btn btn-primary"> 
            Guardar 
        </button>
        <p id="response">{{response}}</p>

        <!--<button type="submit" class="btn btn-primary">
            Guardar cambios
        </button>-->
        
    </form>
    
    <!--
    <button onclick="sendData()" class="btn btn-primary"> 
        Guardar 
    </button>-->
    
</div>
{% endblock %}

{% block extra_js%}
<script src="https://code.jquery.com/jquery-3.5.1.min.js"
        integrity="sha256-9/aliU8dGd2tb6OSsuzixeV4y/faTqgFtohetphbbj0=" crossorigin="anonymous"></script>

<script src="https://cdn.jsdelivr.net/npm/select2@4.1.0-beta.1/dist/js/select2.min.js"></script>



<!-- CONCATENATED FORM -->

<!-- CONCATENATED FORM -->
<script>
    $('.select2').select2();
    // Show list of animal names
    $('#id_animal_name').select2({
        ajax: {
            url: "{% url 'client:get_animal' %}",
            dataType: 'json',
            processResults: function (data) {
                return {
                    results: $.map(data.list_name, function (item) {
                        return {id: item.id, text: item.name};
                    })
                };
            }
        },
        minimumInputLength: 0
    });

    // Show list of animal classes
    $('#id_animal_name').change(function(){
        let aname = $('#id_animal_name option:selected').val();

        document.getElementById("id_animal_class").options.length=0;
        document.getElementById("id_animal_order").options.length=0;
        document.getElementById("id_animal_family").options.length=0;
        document.getElementById("id_animal_genus").options.length=0;
        document.getElementById("id_animal_species").options.length=0;
        document.getElementById("id_animal_origin").options.length=0;

        $('#id_animal_class').select2({
            ajax: {
                url: "{% url 'client:get_animal_class' %}?aname="+aname,
                dataType: 'json',
                processResults: function (data) {
                    return {
                        results: $.map(data.list_classes, function (item) {
                            return {id: item.id, text: item.scientific_name};
                        })
                    };
                }
            },
            minimumInputLength: 0
        });
    });
    // Show list of animal orders
    $('#id_animal_class').change(function(){
        let aclass = $('#id_animal_class option:selected').val();

        document.getElementById("id_animal_order").options.length=0;
        document.getElementById("id_animal_family").options.length=0;
        document.getElementById("id_animal_genus").options.length=0;
        document.getElementById("id_animal_species").options.length=0;
        document.getElementById("id_animal_origin").options.length=0;

        $('#id_animal_order').select2({
            ajax: {
                url: "{% url 'client:get_animal_order' %}?aclass="+aclass,
                dataType: 'json',
                processResults: function (data) {
                    return {
                        results: $.map(data.list_orders, function (item) {
                            return {id: item.id, text: item.scientific_name};
                        })
                    };
                }
            },
            minimumInputLength: 0
        });
    });
    // Show list of animal families
    $('#id_animal_order').change(function(){
        let aorder = $('#id_animal_order option:selected').val();

        document.getElementById("id_animal_family").options.length=0;
        document.getElementById("id_animal_genus").options.length=0;
        document.getElementById("id_animal_species").options.length=0;
        document.getElementById("id_animal_origin").options.length=0;

        $('#id_animal_family').select2({
            ajax: {
                url: "{% url 'client:get_animal_family' %}?aorder="+aorder,
                dataType: 'json',
                processResults: function (data) {
                    return {
                        results: $.map(data.list_families, function (item) {
                            return {id: item.id, text: item.scientific_name};
                        })
                    };
                }
            },
            minimumInputLength: 0
        });
    });
    // Show list of animal genuses
    $('#id_animal_family').change(function(){
        let afamily = $('#id_animal_family option:selected').val();

        document.getElementById("id_animal_genus").options.length=0;
        document.getElementById("id_animal_species").options.length=0;
        document.getElementById("id_animal_origin").options.length=0;

        $('#id_animal_genus').select2({
            ajax: {
                url: "{% url 'client:get_animal_genus' %}?afamily="+afamily,
                dataType: 'json',
                processResults: function (data) {
                    return {
                        results: $.map(data.list_genuses, function (item) {
                            return {id: item.id, text: item.scientific_name};
                        })
                    };
                }
            },
            minimumInputLength: 0
        });
    });
    // Show list of animal species
    $('#id_animal_genus').change(function(){
        let agenus = $('#id_animal_genus option:selected').val();

        document.getElementById("id_animal_species").options.length=0;
        document.getElementById("id_animal_origin").options.length=0;

        $('#id_animal_species').select2({
            ajax: {
                url: "{% url 'client:get_animal_species' %}?agenus="+agenus,
                dataType: 'json',
                processResults: function (data) {
                    return {
                        results: $.map(data.list_species, function (item) {
                            return {id: item.id, text: item.scientific_name};
                        })
                    };
                }
            },
            minimumInputLength: 0
        });
    });
    // Show list of animal origins
    $('#id_animal_species').change(function(){
        let aspecies = $('#id_animal_species option:selected').val();

        document.getElementById("id_animal_origin").options.length=0;

        $('#id_animal_origin').select2({
            ajax: {
                url: "{% url 'client:get_animal_origin' %}?aspecies="+aspecies,
                dataType: 'json',
                processResults: function (data) {
                    return {
                        results: $.map(data.list_origins, function (item) {
                            return {id: item.id, text: item.common_name};
                        })
                    };
                }
            },
            minimumInputLength: 0
        });
    });

    
</script>
    
<!-- SEND DATA TO FORM-->
<script>
    function sendData(){
        //let monitoring_id = $('#monitoring_id').val();
        event.preventDefault();
        
        //get the input value
        $id_animal_name = $('#id_animal_name').val();
        $id_animal_class = $('#id_animal_class').val();
        $id_animal_order = $('#id_animal_order').val();
        $id_animal_family = $('#id_animal_family').val();
        $id_animal_genus = $('#id_animal_genus').val();
        $id_animal_species = $('#id_animal_species').val();
        $id_animal_origin = $('#id_animal_origin').val();
        $id_lifehistory_behavior = $('#id_lifehistory_behavior').val();
        $id_lifehistory_health_condition = $('#id_lifehistory_health_condition').val();
        $id_notes = $('#id_notes').val();

        $.ajax({
            //the url to send the data to
            url: "{% url 'client:detection_create' monitoring_id%}",
            //the data to send to

            data: {
                'csrfmiddlewaretoken':$("input[name=csrfmiddlewaretoken]").val(),
                'animal_name' : $id_animal_name,
                'animal_class' : $id_animal_class,
                'animal_order' : $id_animal_order,
                'animal_family' : $id_animal_family,
                'animal_genus' : $id_animal_genus,
                'animal_species' : $id_animal_species,
                'animal_origin' : $id_animal_origin,
                'lifehistory_behavior' : $id_lifehistory_behavior,
                'lifehistory_health_condition' : $id_lifehistory_health_condition,
                'notes' : $id_notes
            },
            //type. for eg: GET, POST
            type: "POST",
            //datatype expected to get in reply form server
            dataType: "json",
            //on success
            success: function(data){
                //do something after something is recieved from php - response
                alert(data.response);
            },
            //on error
            error: function(){
                //bad request
                //$('#response').text('Error');
                alert(data.response);
            }
        });
    }

</script>
{% endblock %}

client/templates/client_monitoring_update.html
{% extends 'client_base_modal.html' %}
{% load bootstrap4 %}

{% block content %}
    Actualización ID: <strong>{{monitoring_id}}</strong>

    <form method="POST" enctype="multipart/form-data" class="form">
  
        <!--Security token -->
        {% csrf_token %}
        <!-- Using the formset -->
        {% bootstrap_form form %}

        {% buttons %}
        <button type="submit" class="btn btn-primary">
            Guardar cambios
        </button>
        {% endbuttons %}
                          
        <p>{{response}}</p>
    </form>
{% endblock %}